### ISSUE TITLE
Exception thrown when running on API 23 with self-initialization

### ISSUE THREAD

**Issue by sshah112** [marcelpinto/permissions-ktx#14]
Issue is happening when tests are run on API 23. So for the permissions declared that were added on higher android APIs, the library is not able to find it, causing it to throw IllegalArgumentException. When allowing self-initialization https://github.com/marcelpinto/permissions-ktx#self-initialization, tests running on API 23 fail because the callback for shouldShowRequestPermissionRationale goes through the library. 

In this case, client is forced to disable self-initialization and call PermissionProvider.init(context) manually.

```
java.lang.IllegalArgumentException: Unknown permission: android.permission.USE_FULL_SCREEN_INTENT
at android.os.Parcel.readException(Parcel.java:1624)
at android.os.Parcel.readException(Parcel.java:1573)
at android.content.pm.IPackageManager$Stub$Proxy.shouldShowRequestPermissionRationale(IPackageManager.java:2751)
at android.app.ApplicationPackageManager.shouldShowRequestPermissionRationale(ApplicationPackageManager.java:522)
at android.app.Activity.shouldShowRequestPermissionRationale(Activity.java:3874)
at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:553)
at dev.marcelpinto.permissionktx.internal.AndroidPermissionChecker.getRationale(AndroidPermissionChecker.kt:41)
at dev.marcelpinto.permissionktx.internal.AndroidPermissionChecker.getStatus-Jh_E3IQ(AndroidPermissionChecker.kt:31)
at dev.marcelpinto.permissionktx.internal.AndroidPermissionObserver.getPermissionsState(AndroidPermissionObserver.kt:75)
at dev.marcelpinto.permissionktx.internal.AndroidPermissionObserver.refreshStatus(AndroidPermissionObserver.kt:71)
at dev.marcelpinto.permissionktx.internal.AndroidPermissionObserver.onStateChanged(AndroidPermissionObserver.kt:65)
at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:265)
at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:307)
at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
at androidx.lifecycle.ProcessLifecycleOwner.activityResumed(ProcessLifecycleOwner.java:120)
at androidx.lifecycle.ProcessLifecycleOwner$2.onResume(ProcessLifecycleOwner.java:87)
at androidx.lifecycle.ReportFragment.dispatchResume(ReportFragment.java:94)
at androidx.lifecycle.ReportFragment.onResume(ReportFragment.java:115)
at android.app.Fragment.performResume(Fragment.java:2263)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1008)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1130)
at android.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:1963)
at android.app.FragmentController.dispatchResume(FragmentController.java:174)
at android.app.Activity.performResume(Activity.java:6348)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3092)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3134)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2481)
at android.app.ActivityThread.-wrap11(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
at android.os.Handler.dispatchMessage(Handler.java:102)
at androidx.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:53)
at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:155)
at androidx.test.espresso.base.UiControllerImpl.loopMainThreadUntilIdle(UiControllerImpl.java:129)
at com.americanexpress.android.espresso.EspressoInternals$waitForEspressoToIdle$1.run(EspressoInternals.kt:36)
at com.americanexpress.android.espresso.EspressoSugarRunner$runAndWait$booleanFutureTask$1.call(EspressoSugarRunner.kt:149)
at com.americanexpress.android.espresso.EspressoSugarRunner$runAndWait$booleanFutureTask$1.call(EspressoSugarRunner.kt:32)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by sshah112** [comment]
```
java.lang.IllegalArgumentException: Unknown permission: android.permission.USE_FULL_SCREEN_INTENT
at android.os.Parcel.readException(Parcel.java:1624)
at android.os.Parcel.readException(Parcel.java:1573)
at android.content.pm.IPackageManager$Stub$Proxy.shouldShowRequestPermissionRationale(IPackageManager.java:2751)
at android.app.ApplicationPackageManager.shouldShowRequestPermissionRationale(ApplicationPackageManager.java:522)
at android.app.Activity.shouldShowRequestPermissionRationale(Activity.java:3874)
at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:553)
at dev.marcelpinto.permissionktx.internal.AndroidPermissionChecker.getRationale(AndroidPermissionChecker.kt:41)
at dev.marcelpinto.permissionktx.internal.AndroidPermissionChecker.getStatus-Jh_E3IQ(AndroidPermissionChecker.kt:31)
at dev.marcelpinto.permissionktx.internal.AndroidPermissionObserver.getPermissionsState(AndroidPermissionObserver.kt:75)
at dev.marcelpinto.permissionktx.internal.AndroidPermissionObserver.refreshStatus(AndroidPermissionObserver.kt:71)
at dev.marcelpinto.permissionktx.internal.AndroidPermissionObserver.onStateChanged(AndroidPermissionObserver.kt:65)
at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:265)
at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:307)
at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
at androidx.lifecycle.ProcessLifecycleOwner.activityResumed(ProcessLifecycleOwner.java:120)
at androidx.lifecycle.ProcessLifecycleOwner$2.onResume(ProcessLifecycleOwner.java:87)
at androidx.lifecycle.ReportFragment.dispatchResume(ReportFragment.java:94)
at androidx.lifecycle.ReportFragment.onResume(ReportFragment.java:115)
at android.app.Fragment.performResume(Fragment.java:2263)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1008)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1130)
at android.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:1963)
at android.app.FragmentController.dispatchResume(FragmentController.java:174)
at android.app.Activity.performResume(Activity.java:6348)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3092)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3134)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2481)
at android.app.ActivityThread.-wrap11(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
at android.os.Handler.dispatchMessage(Handler.java:102)
at androidx.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:53)
at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:155)
at androidx.test.espresso.base.UiControllerImpl.loopMainThreadUntilIdle(UiControllerImpl.java:129)
at com.americanexpress.android.espresso.EspressoInternals$waitForEspressoToIdle$1.run(EspressoInternals.kt:36)
at com.americanexpress.android.espresso.EspressoSugarRunner$runAndWait$booleanFutureTask$1.call(EspressoSugarRunner.kt:149)
at com.americanexpress.android.espresso.EspressoSugarRunner$runAndWait$booleanFutureTask$1.call(EspressoSugarRunner.kt:32)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by marcelpinto** [comment]
Thanks for reporting. I was not aware that the method would throw IlegalArgumentException. That should be fixed now. Otherwise please open the issue again.

**Comment by sshah112** [comment]
> Thanks for reporting. I was not aware that the method would throw IlegalArgumentException. That should be fixed now. Otherwise please open the issue again.

Issue is resolved on my end, thank you!
