### ISSUE TITLE
Crash when modifing AndroidManifest and removing InitializationProvider

### ISSUE THREAD

**Issue by lectricas** [marcelpinto/permissions-ktx#141]
Modifiing AndriodManifest and adding this:

```
<provider
            android:name="androidx.startup.InitializationProvider"
            android:authorities="${applicationId}.androidx-startup"
            tools:node="remove">
        </provider>
```
causes this crash:

```
 kotlin.UninitializedPropertyAccessException: lateinit property instance has not been initialized
                                                                                                    	at dev.marcelpinto.permissionktx.PermissionProvider$Companion.getInstance(PermissionProvider.kt:48)
                                                                                                    	at dev.marcelpinto.permissionktx.Permission.getStatus-impl(Permission.kt:33)
```

any ideas how to fix this?

**Comment by lectricas** [comment]
I fixed the crash by specifying what initializer I delete:

```
 <provider
    android:name="androidx.startup.InitializationProvider"
    android:authorities="${applicationId}.androidx-startup"
    android:exported="false"
    tools:node="merge">
    <!-- If you are using androidx.startup to initialize other components -->
    <meta-data
        android:name="androidx.work.WorkManagerInitializer"
        android:value="androidx.startup"
        tools:node="remove" />
 </provider>
```
